finance_manager/accounts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, EqualTo, Length, regexp, Email

class RegistrationForm(FlaskForm):
    # Declaring the form's attributes with their validators
    email = StringField(validators=[DataRequired(), Email(message="Invalid email address.")])
    firstname = StringField(validators=[DataRequired(), regexp('^[a-zA-Z\-]+$', message="Invalid first name.")])
    lastname = StringField(validators=[DataRequired(), regexp('^[a-zA-Z\-]+$', message="Invalid last name.")])
    phone = StringField(validators=[DataRequired(), regexp('02\d-\d{8}|011\d-\d{7}|01\d1-\d{7}|01\d{3}-\d{5}|01\d{3}-\d{6}', message="Invalid phone number.")])
    password = PasswordField(validators=[DataRequired(),
                                         Length(8, 15, message="Password must be between 8 and 15 characters long."),
                                         regexp('.*[a-zA-Z\d\!\@\£\$\%\^\&\*\(\)\)\+\=\/\\\?\,\.\<\>\{\}\'\"\#\€\`\~\;\:\-\_\.]',message='Password must contain both one uppercase letter, one lowercase letter, a number and a special character out of the following !@£$%^&*())+=/\?,.<>{}'"#€`~;:-_.")])
    confirm_password = PasswordField(validators=[DataRequired(), EqualTo('password', message="Both password fields must be the equal!\n")])
    submit = SubmitField()

class LoginForm(FlaskForm):
    # Declaring the form's attributes with their validators
    email = StringField(validators=[DataRequired()])
    password = StringField(validators=[DataRequired()])
    submit = SubmitField()

finance_manager/accounts/views.py
from datetime import datetime
from flask import Blueprint, render_template, flash, redirect, url_for, session, request, abort
from finance_manager.accounts.forms import RegistrationForm, LoginForm
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from flask_login import login_user, login_required, current_user
from argon2 import PasswordHasher
import pyotp
from cryptography.fernet import Fernet
from hashlib import scrypt
import base64

# Declaring the password hasher
ph = PasswordHasher()
accounts_bp = Blueprint('accounts', __name__, template_folder='templates')

from finance_manager.config import User, db, app

@accounts_bp.route('/registration', methods=['GET', 'POST'])
def registration():

    # Checking if the user is authenticated as they would have already registered if they are
    if current_user.is_authenticated:
        flash('You have already registered.', category="primary")
        # Redirecting the user to their corresponding page
        if current_user.role == "db_admin":
            return redirect("http://127.0.0.1:5000/admin")
        else:
            return redirect("http://127.0.0.1:5000")
    # Declaring the form
    form = RegistrationForm()
    # Checking if the form is valid
    if form.validate_on_submit():
        # Checking if the email already exists
        if User.query.filter_by(email=form.email.data).first():
            # Alerting the user that the email already exists
            flash('Email already exists', category="danger")
            return render_template('accounts/registration.html', form=form)
        # Hashing the password
        password_hash = ph.hash(form.password.data)
        # Creating the user object to be added
        new_user = User(email=form.email.data, firstname=form.firstname.data, lastname=form.lastname.data, phone=form.phone.data, password=password_hash)
        # Adding the user to the database
        db.session.add(new_user)
        db.session.commit()
        flash('Account Created', category='success')
    # Rendering the registration page
    return render_template('accounts/registration.html', form=form)

@accounts_bp.route('/login', methods=['GET', 'POST'])
@Limiter.limit(self=Limiter(key_func=get_remote_address, app=app), limit_value='20 per minute')
def login():
    # Checking if the user is authenticated as they would have already logged in if they are
    if current_user.is_authenticated:
        flash('You have already logged in.', category="primary")
        # Redirecting the user to their corresponding page
        if current_user.role == "db_admin":
            return redirect("http://127.0.0.1:5000/admin")
        else:
            return redirect("http://127.0.0.1:5000")
    # Setting the authentication attempts to 0 if the user has not already attempted logging in
    if not session.get('authentication_attempts'):
        session['authentication_attempts'] = 0
    # Declaring the form
    form = LoginForm()
    if form.validate_on_submit():
        # Searching for the email
        if User.query.filter_by(email=form.email.data).first():
            # Declaring a user object for the email to compare the values
            userLogin = User.query.filter_by(email=form.email.data).first()
            # Checking if the password is correct and either the pin is correct or MFA is not yet enabled
            if userLogin.verify_password(form.password.data):


                    flash('Login Successful', category='success')
                    session['authentication_attempts'] = 0
                    login_user(userLogin)
                    # Redirecting the user to their corresponding page
                    if current_user.role=="db_admin":
                        return redirect("http://127.0.0.1:5000/admin")
                    else:
                        return redirect("http://127.0.0.1:5000")
            else:
                # If email is correct but password is incorrect an authentication attempt will be added
                session['authentication_attempts'] = session.get('authentication_attempts') + 1
                # If the user has had 3 attempts then they will be locked out
                if session.get('authentication_attempts') >= 3:
                    return render_template('accounts/login.html')
                else:
                    # Alerting the user as to how many attempts they have left
                    flash(('Invalid user details, ' + str(3 - session.get('authentication_attempts')) + ' attempts remaining'), category="danger")
        else:
            session['authentication_attempts'] = session.get('authentication_attempts') + 1
            # If the user has had 3 attempts then they will be locked out
            if session.get('authentication_attempts') >= 3:
                return render_template('accounts/login.html')

            else:
                # Alerting the user as to how many attempts they have left
                flash(('Invalid user details, ' + str(3 - session.get('authentication_attempts')) + ' attempts remaining'), category="danger")
    return render_template('accounts/login.html', form=form)

# Declaring a method to unlock the account after exceeding login attempts
@accounts_bp.route('/unlock')
def unlock():
    session['authentication_attempts'] = 0
    return redirect(url_for('accounts.login'))

finance_manager/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
        <div class="container">
        <h1>Login</h1>
        <div class="p-2 row">
            <div class="col-3"></div>
            <div class="col-6">
                {% if form %}
                <div>
                    <p>Please complete the following form to login.
                    </p>
                </div>
                <form method="POST">
                    <div class="text-left p-2 bg-light border border-primary">
                        <div style="text-align: left">
                            {{ form.csrf_token() }}
                            <div>
                                {% with messages = get_flashed_messages(with_categories=true) %}
                                {% for category, message in messages %}

                                <div class="alert alert-{{ category }} mt-3 alert-dismissible" role="alert">
                                    {{ message }}
                                    <button type="button" class="btn-close" data-bs-dismiss="alert" onclick=delete_flash(this)>
                                        <span>&times;</span>
                                    </button>
                                </div>
                                {% endfor %}
                                {% endwith %}
                            </div>
                            <div class="form-group">
                                {{ form.email.label}}<span class="text-danger">*</span>
                                {{ form.email(class="form-control") }}
                                {{ form.password.label}}<span class="text-danger">*</span>
                                {{ form.password(class="form-control") }}
                                {% for error in form.password.errors %}
                                    {{ error }}
                                {% endfor %}
                            </div>
                        </div>
                        <div>
                            {{ form.submit(class="btn btn-success") }}
                        </div>
                    </div>
                </form>
                {% else %}
                <div class="alert alert-{{ 'danger' }} mt-3 alert-dismissible" role="alert">
                    {{ 'Number of incorrect login attempts exceeded, click' }} <a href="{{ url_for('accounts.unlock') }}">here</a> to unlock account.
                    <button type="button" class="btn-close" data-bs-dismiss="alert" onclick=delete_flash(this)>
                        <span>&times;</span>
                    </button>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

finance_manager/templates/accounts/registration.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <h1>Registration</h1>
        <div class="p-2 row">
            <div class="col-3"></div>
            <div class="col-6">
                <div>
                    <p>Please complete the following form to register an account.
                    </p>
                </div>
                <form method="POST">
                    <div class="text-left p-2 bg-light border border-primary">
                        <div style="text-align: left">
                            {{ form.csrf_token() }}
                            <div>
                                {% with messages = get_flashed_messages(with_categories=true) %}
                                {% for category, message in messages %}
                            <div class="alert alert-{{ category }} mt-3 alert-dismissible" role="alert">
                                {{ message }}. Go to <a href="{{ url_for('accounts.login') }}">login page</a>.
                                <button type="button" class="btn-close" data-bs-dismiss="alert" onclick=delete_flash(this)>
                                    <span>&times;</span>
                                </button>
                            </div>
                            {% endfor %}
                            {% endwith %}
                        </div>
                            <div class="form-group">
                                {{ form.email.label}}<span class="text-danger">*</span>
                                {{ form.email(class="form-control") }}
                                {% for error in form.email.errors %}
                                    {{ error }}
                                {% endfor %}
                                <br>
                                {{ form.firstname.label}}<span class="text-danger">*</span>
                                {{ form.firstname(class="form-control") }}
                                {% for error in form.firstname.errors %}
                                    {{ error }}
                                {% endfor %}
                                <br>
                                {{ form.lastname.label}}<span class="text-danger">*</span>
                                {{ form.lastname(class="form-control") }}
                                {% for error in form.lastname.errors %}
                                    {{ error }}
                                {% endfor %}
                                <br>
                                {{ form.phone.label}}<span class="text-danger">*</span>
                                {{ form.phone(class="form-control") }}
                                {% for error in form.phone.errors %}
                                    {{ error }}
                                {% endfor %}
                                <br>
                                {{ form.password.label}}<span class="text-danger">*</span>
                                {{ form.password(class="form-control") }}
                                {% for error in form.password.errors %}
                                    {{ error }}
                                {% endfor %}
                                <br>
                                {{ form.confirm_password.label}}<span class="text-danger">*</span>
                                {{ form.confirm_password(class="form-control") }}
                                {% for error in form.confirm_password.errors %}
                                    {{ error }}
                                {% endfor %}
                            </div>
                        </div>
                        <div>
                            {{ form.submit(class="btn btn-success") }}
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}